<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  
  <groupId>de.in</groupId>
  <artifactId>jnc</artifactId>
  <version>0.0.1</version>
  <name>jNodeCommander</name>
  <description>Automated SSH and Web-Login Bridge for K8s Nodes</description>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
        <configuration>
          <release>25</release>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>